name: Deploy Azure Function

on:
  push:
    branches:
      - master  # or your default branch
    paths:
      - 'backend/**'  # Only trigger when backend folder changes

env:
  AZURE_FUNCTIONAPP_NAME: 'jemh-functions'  # Replace with your function app name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'       # Path to your function app code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
