name: Deploy Azure Functions

on:
  push:
    paths:
      - './backend'  # Only trigger when something changes in this folder
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: jemh-functions
          package: ./backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
